### ISSUE TITLE
Please upgrade to Guzzle 6.3 for compatibility with PHP 7.x

### ISSUE THREAD

**Issue by jasperoosthoek** [endpot/php-rest-proxy#1]
Using Guzzle 6.0 and PHP 7.x you wil get a warning: 
> Warning: count(): Parameter must be an array or an object that implements Countable in file /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 66

[This was solved in Guzzle 6.3](https://github.com/guzzle/guzzle/issues/1973)

Right now endpot/php-rest-proxy is locked to Guzzle 6.0. Please consider upgrading to the latest version of Guzzle.

**Comment by HunterXuan** [comment]
Fixed in [v1.0.1](https://github.com/endpot/php-rest-proxy/tree/v1.0.1).
Thanks for your feedback.
